version: '3.8'

services:
  node1:
    image: gluster-arm
    container_name: node1
    privileged: true
    volumes:
      - node1-brick:/data/brick
    networks:
      - gluster-net
    command: ["/usr/sbin/glusterd", "-N"]
    tty: true

  node2:
    image: gluster-arm
    container_name: node2
    privileged: true
    volumes:
      - node2-brick:/data/brick
    networks:
      - gluster-net
    command: ["/usr/sbin/glusterd", "-N"]
    tty: true

  node3:
    image: gluster-arm
    container_name: node3
    privileged: true
    volumes:
      - node3-brick:/data/brick
    networks:
      - gluster-net
    command: ["/usr/sbin/glusterd", "-N"]
    tty: true

  node4:
    image: gluster-arm
    container_name: node4
    privileged: true
    volumes:
      - node4-brick:/data/brick
    networks:
      - gluster-net
    command: ["/usr/sbin/glusterd", "-N"]
    tty: true

volumes:
  node1-brick:
    driver: local
  node2-brick:
    driver: local
  node3-brick:
    driver: local
  node4-brick:
    driver: local

networks:
  gluster-net:
    driver: bridge
